[theme]
base = "dark"

# Main colors
primaryColor = "#3B82F6"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#F8FAFC"

[client]
showSidebarNavigation = false

# Borders
showWidgetBorder = true
showSidebarBorder = true

[server]
fileWatcherType = "none"

[runner]
fastReruns = false